### ISSUE TITLE
Getting Access Denied when attempting a download. 

### ISSUE THREAD

**Issue by ewhitebloom** [VeliovGroup/Meteor-Files#216]
I've followed the S3 integration guide, and have basically used the same code, verbatim to do an integration with S3, and then serve the S3 assets through Cloudfront, however I'm only able to download from Cloudfront if I set the S3 bucket to be publicly readable. Otherwise I get an error response like this:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>(request id here)</RequestId>
<HostId>
(id here)=
</HostId>
</Error>
`

I noticed in the example configuration, under the 'Intercept Download' function, there doesn't seem to be any authentication headers to download from S3, as seen here:

Request({
        url: path,
        headers: _.pick(http.request.headers, 'range', 'accept-language', 'accept', 'cache-control', 'pragma', 'connection', 'upgrade-insecure-requests', 'user-agent')
      }).pipe(http.response);
      return true;

Have been struggling with this for awhile. Any feedback is appreciated! Let me know if you need more information.

**Comment by dr-dimitru** [comment]
Hi @ewhitebloom ,

Looks like CORS instruction is not set, please confirm CORS is set as [described here](https://github.com/Lepozepo/S3#4-cors)

**Comment by ewhitebloom** [comment]
Alright, that does get it working. Just FYI the instructions say that only steps 1-3 are necessary, CORS is step 4.

Also, is there a way to get this working without making the bucket public?

**Comment by dr-dimitru** [comment]
Good question, - currently no idea.
I suggest to: 
 1. Close this ticket
 2. Create separate ticket to enhance S3 example with private bucket, I'll lark it as `help wanted`
 3. You can send PR (*if you wish*), or I can update docs with CORS instructions

**Comment by PolGuixe** [comment]
@dr-dimitru 
2. I'd would to see an example for a private bucket. 
3. The docs still need to be updated.

**Comment by PolGuixe** [comment]
I've made a PR for point 3.  
https://github.com/VeliovGroup/Meteor-Files/pull/282

**Comment by lleoooell** [comment]
Hello,

First, thanks a lot for this awesome package !!!

(I'm new to meteor and i come from angular)

Stange thing i don't find out...need a little help/advice...

i was implementing this package since yesterday, everything was working fine with FS,
this morning i try the S3 integration (and i follow this guide with attention : https://github.com/Lepozepo/S3#4-cors), and everything was working fine after 5 minutes, and all my uploads to S3 are ok...and with the link method i could see my pictures...

As i was really excited^^ i wanted to try the remove method...and there troubles begins...
Imediately after my first remove by id, big surprise, all my collection was remove (but i think i know why), but the real issue is that since, all my gets for images are now forbidden with 403, seems like i don't setup any cors rules on S3...wich is not the case of course...

Any advices ? i'm not an Amazon expert also and i'm using the 1.7.5 version of the package...

Thanks for your read...looking forward your answers...
