### ISSUE TITLE
Form submit or click event to upload file(s)

### ISSUE THREAD

**Issue by jdnichollsc** [VeliovGroup/Meteor-Files#320]
Hi guys,

Thanks for this excellent meteor package, is very useful! One question, it's possible to upload files from click or submit events? Exist any example?

Thanks for all and merry Christmas!
Regards, Nicholls

**Comment by jdnichollsc** [comment]
Sorry, works like a charm! Excellent package! :dancing_men:

**Comment by jdnichollsc** [comment]
Of course my friend! Thanks for your hard work!
One question @dr-dimitru, what's the best way to remove files? Exist any method from this package? Or to update files without change the MongoDB id from the files collection?

Thanks in advance, Nicholls

**Comment by dr-dimitru** [comment]
@jdnichollsc 

Take a look on:
 - [`remove`](https://github.com/VeliovGroup/Meteor-Files/wiki/remove) - Which removes both record from DB and File itself
 - [`unlink`](https://github.com/VeliovGroup/Meteor-Files/wiki/unlink) - Low-level method, removes file and subversion from FS, leaving mongo record unchanged

> Or to update files without change the MongoDB id from the files collection?

This is not possible currently even if you know `_id` of recently removed file, due to security concerns

**Comment by dr-dimitru** [comment]
@jdnichollsc you always can hack this by changing file directly on FS at Server side. Fill will remain available as long as path to file mains the same

**Comment by jdnichollsc** [comment]
Excellent, thanks for your help! It's much appreciated! 👍
