### ISSUE TITLE
how to resize original image?

### ISSUE THREAD

**Issue by achtan** [VeliovGroup/Meteor-Files#387]
Hi, is it possible to resize original image?

**Comment by dr-dimitru** [comment]
Yes, take a look on - https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/server/image-processing.js

For resizing before upload read about *Canvas*

**Comment by achtan** [comment]
i meant to resize original image it self (so technically it wont by 'original' image any more :))
my issue is, that i dont wanna store original images on the server, so i have two options:
1. resize original image before it is actually saved
2. copy-resize original image under new version and than delete original version (is it possible to remove 'original' key from 'versions' ?

**Comment by dr-dimitru** [comment]
@achtan ,

Where is files is stored?

**Comment by achtan** [comment]
not sure what U mean... where I store my files? directly on server (no A3 or Dropbox)

**Comment by dr-dimitru** [comment]
Okay, so it's FS, right?

**Comment by achtan** [comment]
yes

**Comment by dr-dimitru** [comment]
Well, no need to involve `versions`.
Just trim/crop/optimize files in `onAfterUpload` hook. I mean update the file using `gm`, without creating the new one.
If size, or other meta-data is changed - update accordingly.

I hope it's clear, let me know.

**Comment by achtan** [comment]
ah ok, so i just rewrite the file, thx

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)

**Comment by achtan** [comment]
done :)

**Comment by Cagdas88** [comment]
@dr-dimitru but what means use "gm" ???

**Comment by dr-dimitru** [comment]
Hello  @Cagdas88 ,

`gm` stands for `graphicsmagick`:
 - Website: http://www.graphicsmagick.org
 - NPM adapter: https://www.npmjs.com/package/gm

**Comment by Vandell63** [comment]
Hey there, 
I would like to use 'gm' but auto resize or crop to not exceed the size of 2MB per example before insert the Image.
Just let the client to make his settings. It will be alert if the size is to larger.
What can you suggest to me ? 
'You specified Read about Canvas' can you suggest some link ? and how can use it with the gm !
Thx in advance

**Comment by dr-dimitru** [comment]
@Vandell63 

 1. Not sure how is easy to implement a tool which will not only change dimensions of the image but it's size. Take a look on [imageoptim](https://imageoptim.com) project, it's opensource.
 2. You may ask a user to choose files with size less than 2MB, and check before upload, see [`onBeforeUpload`](https://github.com/VeliovGroup/Meteor-Files#new-filescollectionconfig-isomorphic) in the README
 3. Canvas is separate solution to alter image dimensions and quality, and it's Client (*Browser*) solution, while gm is Server only (*yes there is ported javascript version of `gm`, with limited features*, haven't tried it before, can't say for its performance)
 4. [Canvas Image Crop Tutorial](http://www.html5canvastutorials.com/tutorials/html5-canvas-image-crop/), for more results use [google](https://www.google.com/search?q=crop+image+javascript+code)
 5. [Image Optimization via Canvas Article](https://www.smashingmagazine.com/2011/08/optimize-images-with-html5-canvas/), for more articles use [google](https://www.google.com/search?q=canvas+reduce+image+size)

Let me know if it helped you.

**Comment by Vandell63** [comment]
Yes @dr-dimitru of course it help me. 'gm' is really great but specially for the 'jpg/jpeg' file. gm not care about the png file infortunatly.
imageoptim is not opensource as i can see...
Thx for link, i know google is here, but great référence by great user will limit hours of research.
Yeah i spent lot of time to find a great solution of optimize images with Meteor easily infornatly not. 
Thx for you response. 
I got an little issue i think it come from the cache but its a bit strange: 
```
	onAfterUpload(file) {
		let img = gm(file.path).quality(80);
		img.resize(1200).write(file.path, (err)=> {
			if(err){
				console.log(err);
			}
		})
	}
```
When the image upload and compress. 2 things happen 
1 - The image taken was the 1rst uploaded it was not the compress one. So in my browser I can see my upload file at 3Mb. In Mongo all fine. In Image Upload Folder i can see the compress image at 800kb strangely.
2 - After Multiple refreshing page, The right compress image appear at the great size...
Is it a caching care ? 
Maybe it because i did not update meta in Mongodb ?? so wich field to update 'meta', 'version' ?
But in few seconde after Images collection update my new compress file in mongodb.
Something that i not understand here.
Thx in advance

**Comment by dr-dimitru** [comment]
> Thx for link, i know google is here, but great référence by great user will limit hours of research.

Sure, but there is not much tools to work with: `gm`, `im` thats it.
[Here is gm flags](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/image-processing.js#L106) we used to optimize image size in demo app.

 1. Might be a result of `onAfterUpload` hook being asynchronous. Library finishes an upload, and ready to serve originally uploaded file. Cutting edge might be caused if you're not creating image subversion, but replacing it.
 2. Always work with disabled network caching

To solve an issue you have described we are waiting for subversion to become available, see [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/listing/listing-row.js#L13) and [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/file/file.js#L57)

**Comment by Vandell63** [comment]
Ho my god we did it. I really never understand the link() expect that it send back the link of the original file.
so the link('compress') will point to my new compress subversion. Do I messed the link() tutorial ? 
Effectively the problem was this one 

`<img src={avatar.link('compress')} alt="" className='full-width' />`

every time it took the "link()" by default even if i specified the 'link('compress') so the strict fixed will be 
`<img src={avatar.versions && avatar.versions.compress && avatar.link('compress')} alt="" className='full-width' />`
AHAHA React fuck you ! it is like the needed user profile data  : `user && user.profile && user.profile.avatar`. aaaaAAAHH Now I Got You ! 

@dr-dimitru thx to you man, You maid an awesome work. My turn now...
I think you package is just the reference for file uploading with Meteor. So if you need support  to get more React example i can help you and this community. Im not an expert but i can help some guys like me. Do you have Gitter ? 

Now pdf upload oooAAARRRGG with preview any tricks ? in the Demo let's read this. ahaha
Thx man,

**Comment by dr-dimitru** [comment]
@Vandell63 great! It took time, but finally solved :)

 1. My thoughts about React - https://twitter.com/smart_egg/status/871480815112392706
 2. I've uploaded [PDF file](https://files.veliov.com/aPyveLTsX52Y8dxqZ) to our demo app, yes it have the preview
 3. [Here is how PDF preview is done in HTML](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/file/file.jade#L33) - basically it's an `iframe` with source of link to the file
 4. Yes, demos, examples, wikis is highly welcome!
 5. [Project Gitter](https://gitter.im/VeliovGroup/Meteor-Files)
 6. [My Gitter](https://gitter.im/dr-dimitru)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
