### ISSUE TITLE
How to install it on cPanel? 

### ISSUE THREAD

**Issue by Cavain** [VeliovGroup/Meteor-Files#466]
Hello,

I have full access to my own server i didn't any solution for cPanel . How can i install Meteor Files on cPanel ? 

Regards

**Comment by dr-dimitru** [comment]
Hello @Cavain ,

Yes, but is requires nodejs to be available on your hosting.
See this thread: https://forums.meteor.com/t/is-it-possible-to-install-meteor-on-a-shared-server-using-cpanel/14874

**Comment by Cavain** [comment]
Hello,

Thanks @dr-dimitru  for your quick response i have nodejs available in my server but the problem is i didn't found any proper tutorial for cPanel Installation if you know how to please replay with details .

Thank You!

**Comment by dr-dimitru** [comment]
@Cavain ,

Can't tell you much as I've never faced cPanel.
All you need is nodejs and mongo. If you know how to run nodejs app via cPanel - you may run Meteor in the same way.

You better to ask at Meteor's forum: https://forums.meteor.com

I'm closing this, since it's not meteor-files package related question.

**Comment by SwiftThemes** [comment]
You can install if you have root access.
Here is how we did using Nginx as reverse proxy and passenger.

http://satishgandham.com/2017/11/installing-meteor-node-js-app-cpanelwhm-based-dedicated-server-vps/
