### ISSUE TITLE
Internet Explorer 11 blank page

### ISSUE THREAD

**Issue by mi-k4** [VeliovGroup/Meteor-Files#480]
Hello, I opened an issue on the forum of Meteor, and after investigation it would seem that the error comes of ostrio:files.

https://forums.meteor.com/t/internet-explorer-11-blank-page/38810

Could you help me ?

thanks and good day

**Comment by dr-dimitru** [comment]
Hello @mi-k4, thank you for submitting this.
Please reopen this issue following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE): 

### I'm having an issue:
 1. Search [issues](https://github.com/VeliovGroup/Meteor-Files/issues), maybe your issue is already solved
 2. We have useful threads makred as [`In a case of the fire - Read This`](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=label%3A%22In%20a%20case%20of%20the%20fire%20-%20Read%20This%22), read them too
 3. Before submitting an issue make sure it's only related to `Meteor-Files` package
 4. If your issue not solved:
     - Give expressive description
     - Version of `Meteor-Files` you're experiencing this issue
     - Version of `Meteor` you're experiencing this issue
     - Is it *Client* or *Server* issue?
     - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
