### ISSUE TITLE
Meteor files does not store on S3

### ISSUE THREAD

**Issue by anaghakomawar** [VeliovGroup/Meteor-Files#486]
Hi,

I am using Meteor Files package. I have included the code given in below link
https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration

I am able to store the video on server, it assume that the video is uploaded on S3 and it unlink the file. In actually the file is not stored on S3. Please help me where I am going wrong.

**Comment by dr-dimitru** [comment]
Hello @anaghakomawar ,

Please reopen this issue following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE): 

### I'm having an issue:
 1. Search [issues](https://github.com/VeliovGroup/Meteor-Files/issues), maybe your issue is already solved
 2. We have useful threads makred as [`In a case of the fire - Read This`](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=label%3A%22In%20a%20case%20of%20the%20fire%20-%20Read%20This%22), read them too
 3. Before submitting an issue make sure it's only related to `Meteor-Files` package
 4. If your issue not solved:
     - Give expressive description
     - Version of `Meteor-Files` you're experiencing this issue
     - Version of `Meteor` you're experiencing this issue
     - Is it *Client* or *Server* issue?
     - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
