### ISSUE TITLE
Error missing method

### ISSUE THREAD

**Issue by alaindixon** [VeliovGroup/Meteor-Files#496]
Hi,

I've got an error when I've tried to upload.
I don't know why but the upload method seems to be unavaible.

Cheers

Alain 
 

![capture d ecran 2017-09-26 a 18 39 08](https://user-images.githubusercontent.com/5199552/30872407-3d01b248-a2ea-11e7-94e8-0f8b47fe4a3e.png)

**Comment by dr-dimitru** [comment]
Hello @alaindixon 

Please reopen this issue following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE): 

### I'm having an issue:
 1. Search [issues](https://github.com/VeliovGroup/Meteor-Files/issues), maybe your issue is already solved
 2. We have useful threads makred as [`In a case of the fire - Read This`](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=label%3A%22In%20a%20case%20of%20the%20fire%20-%20Read%20This%22), read them too
 3. Before submitting an issue make sure it's only related to `Meteor-Files` package
 4. If your issue not solved:
     - Give expressive description
     - Version of `Meteor-Files` you're experiencing this issue
     - Version of `Meteor` you're experiencing this issue
     - Is it *Client* or *Server* issue?
     - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
