### ISSUE TITLE
function addFile dose not set document's _id as mention in document

### ISSUE THREAD

**Issue by tanutapi** [VeliovGroup/Meteor-Files#522]
Reference from https://github.com/VeliovGroup/Meteor-Files/wiki/addFile

> opts.fileId {String} - _id of inserted file, if not set - Random.id() will be used

It seems that addFile() dose not set _id of the new inserted document. I got new generated Random.id() when calling function with fileId set.

**Comment by dr-dimitru** [comment]
Hello @tanutapi ,

Could you please share a piece of code where `addFile` is used.
And update your question according to [our issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by tanutapi** [comment]
I migrated from cfs:gridfs to ostrio:files and my project is quite old. It is still uses METEOR@1.3.2.4 so I got ostrio:files@1.5.2. Today I checked with latest release ostrio:files@1.9.1 and it has no issue anymore. 👍

**Comment by dr-dimitru** [comment]
I'm glad this issue is solved in a simple way :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
