### ISSUE TITLE
link()'s not persistent across meteor restarts

### ISSUE THREAD

**Issue by iwoj** [VeliovGroup/Meteor-Files#524]
I am displaying uploaded images with:

imagesCollection.findOne({_id:id}).link()

And it works fine until I restart meteor, then the links are all broken.

**Comment by dr-dimitru** [comment]
Hello @iwoj ,
Although your issue is clear, please follow [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE) when you're asking for help.

#### TL;TR;
You should change `storagePath` to somewhat outside of your Meteor app, like `/data`. See https://github.com/VeliovGroup/Meteor-Files/issues/250#issuecomment-251300402

You've run into the case described in the [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> On development stage: `yourDevAppDir/.meteor/local/build/programs/server`. __Note: All files will be removed as soon as your application rebuilds or you run meteor reset__. To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

**Comment by dr-dimitru** [comment]
@iwoj have you solved it?

**Comment by iwoj** [comment]
Thanks. This solved the problem.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
