### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by Aur0r** [VeliovGroup/Meteor-Files#64]
Hi,

I wanted to update my packages today and it seems that the Meteor-Files one (ostrio:files) is somehow  broken currently (at least for me).
![nocompatiblebinary](https://cloud.githubusercontent.com/assets/444048/14403906/574d91ca-fe69-11e5-8981-ffc0535b87a3.PNG)

There might have occured an error in one of the later steps of publishing the build.

**Comment by dr-dimitru** [comment]
Hi @Aur0r 
This issue is known, working on it.

__Please let me know which Meteor version and Platform you're on (Win, Mac, Linux)?__

During our investigation, please read [this thread](https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/26) and [this one](https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/32), it's for different package, but with same issue, hope it will help.

**Comment by dr-dimitru** [comment]
Or install:
```shell
meteor add ostrio:files@1.4.0 --allow-incompatible-update
```

v1.4.0 has same codebase, only difference v1.4.1 has explicit dependency for fibers package

**Comment by Aur0r** [comment]
Just to let you know I updated successfully to the newest version and everything works. Thank you again!

**Comment by dr-dimitru** [comment]
Thank you for contribution. BTW, new version is coming :)
