### ISSUE TITLE
fileName not correctly used in .write method

### ISSUE THREAD

**Issue by cmoses8626** [VeliovGroup/Meteor-Files#647]
Great package, thank you!

When writing an image from server side to local file system on the server, I pass in the fileName option in but the actual filename is saved using the _id rather than using fileName. No error messages.

METEOR@1.7.1-rc.5
ostrio:files 1.10.2
Mac 10.13.6, Chrome 69.0.3497.92

Using puppeteer to take a screenshot, then writing this screenshot to local filesystem:
```
  bufferPromise = await page.screenshot();
  Images.write(
    bufferPromise,
    {
      fileName: "logged-in.png",
      type: "image/png"
    },
    (writeError, fileRef) => {
      if (writeError) {
        throw writeError;
      } else {
        console.log(fileRef.name + " is successfully saved to FS.");
      }
    }
  );
```
I'm getting e.g. QM5xuP866Hjva9DhX.png rather than logged-in.png.

**Comment by dr-dimitru** [comment]
Hello @cmoses8626 ,

`fileName` option is only used to set name of the file in the response headers (e.g. when downloaded via browser).
It is not possible to alter name of the file on FS, due to security policy, this was widely discussed in our community and we decided to keep name of the file on FS in control of the library.

**Comment by cmoses8626** [comment]
Got it, closing issue. Thx!
