### ISSUE TITLE
Large file upload performance?

### ISSUE THREAD

**Issue by phucnv206** [VeliovGroup/Meteor-Files#68]
Hi Meteor-Files team,

Any solution for upload a file ~10GB via DDP without RAM dependence?
I'm building a storage service and allow user upload file(s) in any size.

**Comment by dr-dimitru** [comment]
Hi @phucnv206 
On server there is no RAM dependance, all incoming chunks is directly goes to FS.
In browser, it depends only from [`FileReader`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) behavior 

Have you tried to test it, within large files??

**Comment by dr-dimitru** [comment]
Hi @phucnv206 
This issue is solved in [v1.4.3](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.4.3)
Tweak `chunkSize` and `streams` properties to meet your needs, or use `dynamic` for better balance between small and large files, [read more](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))
