### ISSUE TITLE
Can we watch for Dropbox changes?

### ISSUE THREAD

**Issue by dpatte** [VeliovGroup/Meteor-Files#695]
If I use Dropbox as my file storage, can I watch or scan for changes at Dropbox initiated from outside my Meteor app?

**Comment by dr-dimitru** [comment]
Hello @dpatte ,

Short answer is  — Yes, using [its latest API](https://dropbox.github.io/dropbox-sdk-js/Dropbox.html#filesListFolderLongpoll__anchor).
Long answer — we have no example on this, you've got to implement it on your own.

Let me know if it helped you in any way.

Feel free to close it in case if the issue is solved on your end.

**Comment by dpatte** [comment]
It looks like I may attempt to implement a solution using their api. I'll let you know how it goes.
