### ISSUE TITLE
Heroku demo currently doesn't show the uploaded files correctly

### ISSUE THREAD

**Issue by Aur0r** [VeliovGroup/Meteor-Files#70]
It is just a minor thing since everything is working at my end. But the demo hosted on heroku doesn't show the uploaded files correctly.

I guess they are not uploaded anymore since they might get wiped if you redeloy the instance on heroku but the database still shows the upload entries.

https://meteor-files.herokuapp.com/kB6cioBNDCLsWepqs:
![herokudemofilesnotshown](https://cloud.githubusercontent.com/assets/444048/14490157/8ae8f136-0171-11e6-91aa-e0d7fec87891.PNG)

**Comment by dr-dimitru** [comment]
Hi @Aur0r 
This is caused by "ephemeral filesystem", which is used by Heroku. [Read SO thread](http://stackoverflow.com/questions/12416738/how-to-use-herokus-ephemeral-filesystem) and [Heroku docs](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem).
Basically it  means - Heroku has FS, but you can store files only during current session.
We are working on it. Further versions will store Files on Google Drive, examples will be published in docs section.

We are really missing Meteor's free hosting.

**Comment by dr-dimitru** [comment]
Hi @Aur0r thank you for contribution.
This issue is solved in [v1.4.3](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.4.3)
Read more about [third-party storage](https://github.com/VeliovGroup/Meteor-Files/wiki/Third-party-storage)
