### ISSUE TITLE
Is the idea of uploading via WebRTC abandoned?

### ISSUE THREAD

**Issue by SimonSimCity** [VeliovGroup/Meteor-Files#712]
The branch https://github.com/VeliovGroup/Meteor-Files/tree/webrtc-data-channel of this project hasn't been updated in 3 years. Does this mean this idea is abandoned, or was there simply not have the time to complete it yet?

In case it's abandoned it would be nice to post an update about it. If not, I'd like to know a reason why it still could be a better idea over DDP or HTTP.

**Comment by dr-dimitru** [comment]
> Does this mean this idea is abandoned, or was there simply not have the time to complete it yet?

Yes, it's abandoned

> was there simply not have the time to complete

No, it happened due to lack of interest among our users (developers). I've raised a question few times with no response.

> In case it's abandoned it would be nice to post an update about it. If not, I'd like to know a reason why it still could be a better idea over DDP or HTTP.

Current status: It was successful experiment, we succeed in transferring data from browser to server over webRTC. Due to complexity and immaturity of technology its development would mean a lot of extra hours, including later hours of maintenance. As community had no interest, webRTC branch was abandoned and never merged to master.

**Comment by SimonSimCity** [comment]
Thanks for the quick response.

Is there a real chance for webRTC to become a better choice than HTTP? On the branch I read that HTTP already was 2x faster than the current webRTC implementation, so if this implementation isn't particularly slow, it must have other benefits in order to prove itself worthy for other use-cases. Do you see any?

Just asking because I haven't seen a ticket about webRTC yet which would document your thoughts and insight on this.

**Comment by dr-dimitru** [comment]
> Is there a real chance for webRTC to become a better choice than HTTP

It's will be just different, not better, not worse. In terms of speed, it might be slower than HTTP due to limits of package size in UDP and RTC/DC. But it definitely would be the overcomplicated solution, as it involves STUN and TURN servers you need to run (or rent out for production) and signaling. Signaling is covered, thanks to DDP, while TURN and STUN is the something you need to run and maintain and are necessary parts of communication, in real-world there's not much p2p (*direct*, in terms of networking) connections.

And you shouldn't forget we are discussing browser-to->server connection, while WebRTC was created for two-way browser<-to->browser connection. I believe WebRTC is the wrong technology (*tool*) for this purpose (*task*)
