### ISSUE TITLE
Xss attack trough file name or extension?

### ISSUE THREAD

**Issue by gjdanskij** [VeliovGroup/Meteor-Files#720]
Is there any tag filtering on the file name, before inserting it in database? I see its checked with `isString`  and regex that replaces commas, slashes and whitespaces i think.

**Comment by dr-dimitru** [comment]
@gjdanskij please point to the code

**Comment by gjdanskij** [comment]
https://github.com/VeliovGroup/Meteor-Files/blob/aeaac0ee9020644c0fcc292635fc1d746f58844a/core.js#L120

There is the name handler right?

**Comment by dr-dimitru** [comment]
@gjdanskij file name is used only as *String* stored in DB. It isn't used as actual file name on FS or anywhere else.

What kind of XSS is on your mind? We can run tests

**Comment by gjdanskij** [comment]
I was worried because i was outputting the name from database `{{file.name}}` directly into template (spacebars ).

**Comment by dr-dimitru** [comment]
@gjdanskij for double-checking uploaded file I recommend to use [`onAfterUpload` hook](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md) or [`afterUpload` event](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md#event-map) and update MongoDB record if needed.

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
