### ISSUE TITLE
How do I change storagePath during upload? I want to use same collection but want to change path based on current module. Is it possible?

### ISSUE THREAD

**Issue by pdshah3690** [veliovgroup/Meteor-Files#782]
```
export const Uploads = new FilesCollection({
    collectionName: 'uploads',
    allowClientCode: false,
    storagePath: "/Applications/Ampps/www/elaadmin/public/",
    onBeforeUpload(file) {
        if (/jpeg|png|jpg/i.test(file.extension)) {
            return true;
        } else {
            return "Invalid file format";
        }
    }
});
```

**Comment by dr-dimitru** [comment]
Hello @pdshah3690,

[`storagePath` can be a function](https://github.com/veliovgroup/Meteor-Files/blob/master/server.js#L275) and invoked with [`fileRef` upon upload](https://github.com/veliovgroup/Meteor-Files/blob/master/server.js#L926). See mode details in the [`Constructor` docs](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md)

Feel free to close it in case if the issue is solved on your end.

**Comment by pdshah3690** [comment]
@dr-dimitru It worked. Thanks for this solution.

```
export const Uploads = new FilesCollection({
    collectionName: 'uploads',
    allowClientCode: false,
    storagePath: function(file) {
        return "/Applications/Ampps/www/elaadmin/public/uploads/"+file.meta.type+"/";
    },
    onBeforeUpload(file) {
        if (/jpeg|png|jpg/i.test(file.extension)) {
            return true;
        } else {
            return "Invalid file format";
        }
    }
});
```

**Comment by dr-dimitru** [comment]
@pdshah3690 I'm glad you solved it so quickly.

-----


Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
